"""Public FixedFontOCR API."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from .backends import (
    AutoBackend,
    Backend,
    CPUBackend,
    WGPUBackend,
    benchmark_backends,
)
from .decoder import DecoderConfig
from .frontend import extract_frontend
from .geometry import char_geometry
from .lexicon import Lexicon, apply_lexicon, is_lexicon_ref, load_lexicon
from .model import load_model
from .postprocess import allowed_ids as build_allowed_ids
from .preprocess import find_lines
from .scorer import SegmentScorer
from .segmentation import segment_line
from .types import (
    CharResult,
    DecodePath,
    OCRResult,
    Profile,
    VisualCandidate,
    default_profile,
)

UNKNOWN_CHAR = "?"


@dataclass
class FixedFontOCR:
    """Fixed-font OCR engine.

    Parameters
    ----------
    model_path:
        Directory containing ``config.json``, ``charset.txt`` and
        ``weights.bin`` (generated by ``fixedfontocr-generate``).
    backend:
        ``"cpu"`` selects the numpy TinyCNN backend (or the template
        matcher), ``"wgpu"`` the WGPU compute backend for tinycnn/hybrid
        models. ``"auto"`` (default) benchmarks CPU vs WGPU at batch sizes
        1/8/16/32/64/128 during construction, records the crossover, and then
        picks the faster backend per actual batch size at runtime.
    profile:
        Segmentation profile. When ``None``, a default profile is used.
    auto_benchmark:
        Only used with ``backend="auto"``. When False the engine skips the
        startup benchmark and falls back to the CPU backend.
    auto_batch_sizes:
        Only used with ``backend="auto"``. Batch sizes measured during the
        startup benchmark.
    """

    model_path: str | Path
    backend: str = "auto"
    profile: Profile | None = None
    auto_benchmark: bool = True
    auto_batch_sizes: tuple[int, ...] = (1, 8, 16, 32, 64, 128)

    def __post_init__(self) -> None:
        if self.backend not in ("auto", "cpu", "wgpu"):
            raise ValueError(
                f"backend {self.backend!r} is not supported; use 'cpu', 'wgpu' or 'auto'"
            )
        self.model = load_model(Path(self.model_path))
        self.profile = self.profile or default_profile()
        self._benchmark: dict[int, dict[str, float]] | None = None
        self._benchmark_error: str | None = None
        self._backend: Backend | None = None
        self._cnn_threshold = float(self.model.config.get("cnn_threshold", 0.0))

        # P0-4 backend boundary: the same backend that scores every lattice
        # candidate is created first and injected into SegmentScorer. No OCR
        # stage below it (and no second classification after the decoder)
        # ever calls a classifier on its own.
        if self.model.classifier in ("tinycnn", "hybrid"):
            self._backend = self._make_backend()
        elif self.backend == "wgpu":
            raise ValueError(
                "WGPU backend requires a tinycnn model; template models run on CPU"
            )
        self._scorer = SegmentScorer(self.model, cnn_backend=self._backend)

    # ------------------------------------------------------------------
    # Backend selection
    # ------------------------------------------------------------------

    def _make_backend(self) -> Backend:
        if self.backend == "wgpu":
            return WGPUBackend(
                weights=self.model.weights,
                input_size=self.model.input_size,
            )
        cpu = CPUBackend(
            weights=self.model.weights,
            input_size=self.model.input_size,
        )
        if self.backend == "cpu" or not self.auto_benchmark:
            return cpu
        try:
            gpu = WGPUBackend(
                weights=self.model.weights,
                input_size=self.model.input_size,
            )
        except Exception as exc:  # no adapter / driver
            self._benchmark_error = f"wgpu unavailable: {exc}"
            return cpu
        try:
            measurements = benchmark_backends(cpu, gpu, self.auto_batch_sizes)
        except Exception as exc:
            self._benchmark_error = f"backend benchmark failed: {exc}"
            return cpu
        self._benchmark = measurements
        return AutoBackend(cpu=cpu, gpu=gpu, measurements=measurements)

    @property
    def backend_benchmark(self) -> dict[int, dict[str, float]] | None:
        """CPU/GPU latency table measured at construction (``auto`` only)."""
        return self._benchmark

    @property
    def backend_benchmark_error(self) -> str | None:
        """Why ``auto`` fell back to CPU, if it did."""
        return self._benchmark_error

    @property
    def resolved_backend(self) -> str:
        """Backend name after auto-selection: ``cpu``, ``wgpu`` or ``auto``."""
        if self.backend != "auto":
            return self.backend
        if isinstance(self._backend, AutoBackend):
            return "auto"
        return "cpu"

    # ------------------------------------------------------------------
    # Recognition
    # ------------------------------------------------------------------

    def recognize(
        self,
        image: NDArray[np.uint8],
        allowed_chars: str | None = None,
        *lexicon_args,
        lexicon: str | Path | Lexicon | None = None,
        lexicon_mode: str | None = None,
    ) -> OCRResult:
        """Recognize horizontal, single-line text in ``image``.

        ``image`` must have shape ``(H, W, 3)`` and dtype ``uint8``.
        ``allowed_chars`` optionally restricts the classifier's output
        alphabet (e.g. ``"0123456789"`` for a coin counter). Characters
        outside the set are never emitted; when no candidate survives, the
        position is reported as ``"?"`` with confidence 0.

        ``lexicon`` selects a Goal 11 dictionary (``"ships"``,
        ``"equipment"``, ``"ui"`` or ``"all"``, a ``Lexicon``, or a path to
        a one-word-per-line file). ``lexicon_mode`` is ``"none"`` (default
        when no lexicon is supplied), ``"prefer"`` (default when a lexicon
        is supplied), ``"topk"`` or ``"strict"``. The visible ``text`` is
        never rewritten in ``prefer`` unless the lexicon target is already a
        visually plausible Top-K alternative for a low-confidence character.
        ``"topk"`` is the "Top-3 取词表" mode: when the visible text is not
        itself a dictionary term it promotes the first decoder alternative
        that is an exact term, or rewrites from the per-position visual
        Top-3 when a term is fully supported by those alternatives (unique
        matches only). Goal 12 partial words follow the same rule: a screen
        crop keeps its visible ``text`` and only annotates
        ``matched_term``/``matched_span`` (for example ``text="尔的摩"``,
        ``matched_term="巴尔的摩"``, ``matched_span=(1, 4)``). ``strict``
        rejects non-exact text with an empty result.
        """

        image = np.asarray(image)
        if image.ndim != 3 or image.shape[2] != 3:
            raise ValueError(f"expected RGB image with shape (H, W, 3), got {image.shape}")
        if image.dtype != np.uint8:
            raise ValueError(f"expected uint8 image, got {image.dtype}")

        if len(lexicon_args) >= 1 and lexicon is None:
            if is_lexicon_ref(allowed_chars):
                if lexicon_mode is None:
                    lexicon_mode = lexicon_args[0]
            else:
                lexicon = lexicon_args[0]
        if len(lexicon_args) >= 2 and lexicon_mode is None:
            if not is_lexicon_ref(allowed_chars):
                lexicon_mode = lexicon_args[1]
        if len(lexicon_args) > 2:
            raise TypeError("recognize() takes at most 4 positional arguments")

        # ``recognize(image, "ships", "prefer")`` is accepted as shorthand
        # for the keyword form while keeping the existing positional
        # ``allowed_chars`` API intact.
        if lexicon is None and is_lexicon_ref(allowed_chars):
            lexicon = allowed_chars
            allowed_chars = None
        if lexicon_mode is None:
            lexicon_mode = "prefer" if lexicon is not None else "none"
        lexicon_mode = str(lexicon_mode).strip().lower()
        if lexicon_mode not in ("none", "prefer", "topk", "strict"):
            raise ValueError(
                f"lexicon_mode {lexicon_mode!r} is not supported; "
                "use 'none', 'prefer', 'topk' or 'strict'"
            )
        if lexicon_mode != "none" and lexicon is None:
            raise ValueError(
                "lexicon must be provided when lexicon_mode is not 'none'"
            )

        allowed = build_allowed_ids(self.model.charset, allowed_chars)
        if lexicon_mode == "strict" and lexicon is not None:
            lexicon_ids = build_allowed_ids(
                self.model.charset, load_lexicon(lexicon).charset
            )
            if allowed is None:
                allowed = lexicon_ids
            elif lexicon_ids is not None:
                allowed &= lexicon_ids
        frontend = extract_frontend(image, self.profile)
        mask = frontend.binary_mask
        paths: list[DecodePath] = []
        decoded: list[tuple[VisualCandidate, str, float]] = []
        for line in find_lines(mask, self.profile):
            path = segment_line(
                line,
                self.profile,
                self._scorer,
                allowed,
                soft=frontend.soft_foreground,
                lexicon=lexicon if lexicon_mode != "none" else None,
                decoder_config=DecoderConfig(),
            )
            if not path.candidates:
                continue
            paths.append(path)
            # P0-1: DecodePath is the single classification authority. The
            # lattice candidates were classified exactly once inside
            # segment_line(); here we only project the chosen char_ids and
            # their own candidate.scores entries into public CharResults.
            char_ids = path.char_ids or ()
            for i, cand in enumerate(path.candidates):
                cid = (
                    int(char_ids[i])
                    if i < len(char_ids)
                    else self._top_char_id(cand)
                )
                char, conf = self._path_char_result(cand, cid)
                decoded.append((cand, char, conf))

        if not decoded:
            return OCRResult(text="", confidence=0.0, chars=(), alternatives=())

        text = "".join(char for _, char, _ in decoded)
        confidence = float(
            np.mean([conf for _, _, conf in decoded])
        ) if decoded else 0.0
        chars = tuple(
            CharResult(
                char=char,
                x=cand.segment.x,
                y=cand.segment.y,
                w=cand.segment.w,
                h=cand.segment.h,
                confidence=conf,
            )
            for cand, char, conf in decoded
        )
        result = OCRResult(
            text=text,
            confidence=confidence,
            chars=chars,
            matched_term=None,
            matched_span=None,
            alternatives=self._alternatives(paths),
            lexicon_match=None,
            path=paths[0] if len(paths) == 1 else None,
        )
        return apply_lexicon(
            result,
            lexicon,
            lexicon_mode,
            charset=self.model.charset,
        )

    def _top_char_id(self, candidate: VisualCandidate) -> int:
        """Top-1 char id used when a legacy path carries no decoder char_ids."""
        if candidate.scores is not None and candidate.scores.char_ids:
            return int(candidate.scores.char_ids[0])
        if candidate.score is not None:
            return int(getattr(candidate.score, "char_id", -1))
        return -1

    def _chosen_geometry(
        self,
        candidate: VisualCandidate,
        char_id: int,
    ) -> float:
        """Geometry for the decoder-chosen ``(candidate, char_id)`` pair.

        Mirrors the decoder: candidate-level geometry is precomputed on the
        lattice candidate, while the character-specific half is computed for
        this particular char_id.
        """

        base = candidate.candidate_geometry
        if base is None:
            # Legacy/manual candidates only carry the old full Top-1 scalar.
            return float(candidate.geometry_score)
        score = candidate.score
        if (
            score is not None
            and getattr(score, "char_id", -1) == int(char_id)
            and getattr(score, "score_type", "") == "template"
            and getattr(score, "template_raw_score", 0.0) >= 1.0 - 1e-9
            and candidate.geometry_score == 0.0
        ):
            return 0.0
        total = base + char_geometry(
            candidate,
            int(char_id),
            self.model.geometry,
            normalize_geometry=candidate.normalize_geometry,
        )
        return float(max(total, -0.12))

    def _path_char_result(
        self,
        candidate: VisualCandidate,
        char_id: int,
    ) -> tuple[str, float]:
        """Project one decoded candidate into ``(char, confidence)``.

        This performs no classifier work. It keeps the model's unknown gate
        (no allowed class / below CNN threshold) authoritative, then uses
        the chosen character's own Top-K visual score and its per-character
        geometry.
        """

        if (
            char_id < 0
            or int(char_id) >= len(self.model.charset)
            or self._candidate_char(candidate) == UNKNOWN_CHAR
        ):
            return UNKNOWN_CHAR, 0.0
        cid = int(char_id)
        geometry = self._chosen_geometry(candidate, cid)
        _visual, confidence = self._scorer.finalize_char_score(
            candidate, cid, geometry
        )
        return self.model.charset[cid], confidence

    def _candidate_char(self, candidate: VisualCandidate) -> str:
        """Visible character for one chosen lattice candidate."""
        score = candidate.score
        if score is None or score.char_id < 0:
            return UNKNOWN_CHAR
        if (
            score.score_type == "cnn"
            and score.raw_score < getattr(self, "_cnn_threshold", 0.0)
        ):
            return UNKNOWN_CHAR
        return self.model.charset[int(score.char_id)]

    def _alternatives(self, paths: list[DecodePath]) -> tuple[str, ...]:
        """Goal 13 decoder alternatives, with Top-K substitution fallback."""
        out: list[str] = []
        for path in paths:
            for alt in path.alternatives:
                if alt and alt not in out:
                    out.append(alt)
            if len(out) >= 8:
                return tuple(out[:8])
        for path in paths:
            chars = [self._candidate_char(c) for c in path.candidates]
            base = "".join(chars)
            for i, cand in enumerate(path.candidates):
                scores = cand.scores
                if scores is None or len(scores.char_ids) < 2:
                    continue
                second_id = int(scores.char_ids[1])
                if second_id < 0 or second_id >= len(self.model.charset):
                    continue
                alt = list(chars)
                alt[i] = self.model.charset[second_id]
                text = "".join(alt)
                if text != base and text not in out:
                    out.append(text)
        return tuple(out[:8])

    # ------------------------------------------------------------------
    # Cross-frame tracking (Goal 16)
    # ------------------------------------------------------------------

    def tracker(self, **kwargs) -> "FrameTracker":
        """Build a :class:`FrameTracker` for this OCR engine.

        The tracker is a separate stateful layer: it never mutates this
        engine, so :meth:`recognize` remains a pure single-frame function.
        """

        from .tracker import FrameTracker

        return FrameTracker(self, **kwargs)
