"""Public FixedFontOCR API."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from .backends import (
    AutoBackend,
    Backend,
    CPUBackend,
    WGPUBackend,
    benchmark_backends,
)
from .classifier import Classifier, TemplateClassifier
from .cnn import forward
from .frontend import extract_frontend
from .model import load_model
from .postprocess import allowed_ids as build_allowed_ids
from .postprocess import pick
from .preprocess import find_lines, normalize
from .scorer import SegmentScorer, to_confidence
from .segmentation import segment_line
from .types import (
    CharResult,
    Component,
    DecodePath,
    OCRResult,
    Profile,
    VisualCandidate,
    default_profile,
)

UNKNOWN_CHAR = "?"


@dataclass
class FixedFontOCR:
    """Fixed-font OCR engine.

    Parameters
    ----------
    model_path:
        Directory containing ``config.json``, ``charset.txt`` and
        ``weights.bin`` (generated by ``fixedfontocr-generate``).
    backend:
        ``"cpu"`` selects the numpy TinyCNN backend (or the template
        matcher), ``"wgpu"`` the WGPU compute backend for tinycnn/hybrid
        models. ``"auto"`` (default) benchmarks CPU vs WGPU at batch sizes
        1/8/16/32/64/128 during construction, records the crossover, and then
        picks the faster backend per actual batch size at runtime.
    profile:
        Segmentation profile. When ``None``, a default profile is used.
    auto_benchmark:
        Only used with ``backend="auto"``. When False the engine skips the
        startup benchmark and falls back to the CPU backend.
    auto_batch_sizes:
        Only used with ``backend="auto"``. Batch sizes measured during the
        startup benchmark.
    """

    model_path: str | Path
    backend: str = "auto"
    profile: Profile | None = None
    auto_benchmark: bool = True
    auto_batch_sizes: tuple[int, ...] = (1, 8, 16, 32, 64, 128)

    def __post_init__(self) -> None:
        if self.backend not in ("auto", "cpu", "wgpu"):
            raise ValueError(
                f"backend {self.backend!r} is not supported; use 'cpu', 'wgpu' or 'auto'"
            )
        self.model = load_model(Path(self.model_path))
        self.profile = self.profile or default_profile()
        self._scorer = SegmentScorer(self.model)
        self._normalize_spec = self.model.normalize_spec
        self._benchmark: dict[int, dict[str, float]] | None = None
        self._benchmark_error: str | None = None
        self._backend: Backend | None = None

        if self.model.classifier in ("tinycnn", "hybrid"):
            self._backend: Backend = self._make_backend()
        else:
            if self.backend == "wgpu":
                raise ValueError(
                    "WGPU backend requires a tinycnn model; template models run on CPU"
                )
            self._classifier: Classifier = TemplateClassifier(
                templates=self.model.templates,
                charset=self.model.charset,
                input_size=self.model.input_size,
                normalize_spec=self.model.normalize_spec,
            )
        if self.model.classifier == "hybrid":
            self._template_classifier = TemplateClassifier(
                templates=self.model.templates,
                charset=self.model.charset,
                input_size=self.model.input_size,
                normalize_spec=self.model.normalize_spec,
            )
            self._template_threshold = float(
                self.model.config.get("template_threshold", 0.90)
            )
            self._cnn_threshold = float(
                self.model.config.get("cnn_threshold", 0.0)
            )

    # ------------------------------------------------------------------
    # Backend selection
    # ------------------------------------------------------------------

    def _make_backend(self) -> Backend:
        if self.backend == "wgpu":
            return WGPUBackend(
                weights=self.model.weights,
                input_size=self.model.input_size,
            )
        cpu = CPUBackend(
            weights=self.model.weights,
            input_size=self.model.input_size,
        )
        if self.backend == "cpu" or not self.auto_benchmark:
            return cpu
        try:
            gpu = WGPUBackend(
                weights=self.model.weights,
                input_size=self.model.input_size,
            )
        except Exception as exc:  # no adapter / driver
            self._benchmark_error = f"wgpu unavailable: {exc}"
            return cpu
        try:
            measurements = benchmark_backends(cpu, gpu, self.auto_batch_sizes)
        except Exception as exc:
            self._benchmark_error = f"backend benchmark failed: {exc}"
            return cpu
        self._benchmark = measurements
        return AutoBackend(cpu=cpu, gpu=gpu, measurements=measurements)

    @property
    def backend_benchmark(self) -> dict[int, dict[str, float]] | None:
        """CPU/GPU latency table measured at construction (``auto`` only)."""
        return self._benchmark

    @property
    def backend_benchmark_error(self) -> str | None:
        """Why ``auto`` fell back to CPU, if it did."""
        return self._benchmark_error

    @property
    def resolved_backend(self) -> str:
        """Backend name after auto-selection: ``cpu``, ``wgpu`` or ``auto``."""
        if self.backend != "auto":
            return self.backend
        if isinstance(self._backend, AutoBackend):
            return "auto"
        return "cpu"

    # ------------------------------------------------------------------
    # Recognition
    # ------------------------------------------------------------------

    def recognize(
        self,
        image: NDArray[np.uint8],
        allowed_chars: str | None = None,
    ) -> OCRResult:
        """Recognize horizontal, single-line text in ``image``.

        ``image`` must have shape ``(H, W, 3)`` and dtype ``uint8``.
        ``allowed_chars`` optionally restricts the classifier's output
        alphabet (e.g. ``"0123456789"`` for a coin counter). Characters
        outside the set are never emitted; when no candidate survives, the
        position is reported as ``"?"`` with confidence 0.
        """

        image = np.asarray(image)
        if image.ndim != 3 or image.shape[2] != 3:
            raise ValueError(f"expected RGB image with shape (H, W, 3), got {image.shape}")
        if image.dtype != np.uint8:
            raise ValueError(f"expected uint8 image, got {image.dtype}")

        allowed = build_allowed_ids(self.model.charset, allowed_chars)
        frontend = extract_frontend(image, self.profile)
        mask = frontend.binary_mask
        paths: list[DecodePath] = []
        decoded: list[tuple[VisualCandidate, str, float]] = []
        for line in find_lines(mask, self.profile):
            path = segment_line(
                line,
                self.profile,
                self._scorer,
                allowed,
                soft=frontend.soft_foreground,
            )
            if not path.candidates:
                continue
            segments = [c.segment for c in path.candidates]
            geometries = [c.normalize_geometry for c in path.candidates]
            if self.model.classifier == "template":
                glyphs = self._binary_glyph_batch(segments, geometries)
                tb = self._classifier.match_batch(glyphs, allowed)
                for i, cand in enumerate(path.candidates):
                    cid = int(tb.ids[i])
                    if cid < 0:
                        decoded.append((cand, UNKNOWN_CHAR, 0.0))
                    else:
                        decoded.append(
                            (
                                cand,
                                self.model.charset[cid],
                                to_confidence(float(tb.scores[i]), "template"),
                            )
                        )
            else:
                if self.model.input_mode == "soft":
                    glyphs = frontend.soft_glyph_batch(
                        segments,
                        self.model.input_size,
                        geometries=geometries,
                        spec=self._normalize_spec,
                    )
                    cnn_soft = frontend.soft_foreground
                else:
                    glyphs = self._binary_glyph_batch(segments, geometries)
                    cnn_soft = None
                if self.model.classifier == "hybrid":
                    pairs = self._classify_hybrid(
                        path.candidates,
                        glyphs,
                        allowed,
                        soft=cnn_soft,
                        geometries=geometries,
                    )
                else:
                    result = self._backend.classify(glyphs)
                    pairs = self._classify_backend(
                        path.candidates, glyphs, result, allowed
                    )
                decoded.extend(
                    (cand, char, conf)
                    for cand, (char, conf) in zip(path.candidates, pairs)
                )
            paths.append(path)

        if not decoded:
            return OCRResult(text="", confidence=0.0, chars=(), alternatives=())

        text = "".join(char for _, char, _ in decoded)
        confidence = float(
            np.mean([conf for _, _, conf in decoded])
        ) if decoded else 0.0
        chars = tuple(
            CharResult(
                char=char,
                x=cand.segment.x,
                y=cand.segment.y,
                w=cand.segment.w,
                h=cand.segment.h,
                confidence=conf,
            )
            for cand, char, conf in decoded
        )
        return OCRResult(
            text=text,
            confidence=confidence,
            chars=chars,
            matched_term=None,
            matched_span=None,
            alternatives=self._alternatives(paths),
            lexicon_match=None,
            path=paths[0] if len(paths) == 1 else None,
        )

    def _binary_glyph_batch(
        self,
        segments: list[Component],
        geometries: list[tuple[float, float] | None] | None = None,
    ) -> NDArray[np.uint8]:
        """Normalize binary candidate masks (Goal 3 baseline frame)."""

        geoms = geometries or [None] * len(segments)
        spec = self._normalize_spec
        if spec is None:
            return np.stack(
                [normalize(s.mask, self.model.input_size) for s in segments]
            )
        return np.stack(
            [
                (
                    normalize(s.mask, self.model.input_size)
                    if g is None
                    else normalize(
                        s.mask,
                        self.model.input_size,
                        baseline_offset=g[0],
                        scale=g[1],
                        baseline_row=spec.baseline_row,
                    )
                )
                for s, g in zip(segments, geoms)
            ]
        )

    def _classify_backend(
        self,
        candidates: list[VisualCandidate],
        glyphs: NDArray[np.uint8],
        result,
        allowed: set[int] | None,
    ) -> list[tuple[str, float]]:
        """Map a backend result to (char, confidence), masking disallowed picks."""
        n = len(candidates)
        if n == 0:
            return []
        pairs: list[tuple[str, float] | None] = [None] * n
        remask: list[int] = []
        for i, (_, char_id, score) in enumerate(
            zip(candidates, result.char_ids, result.scores)
        ):
            if allowed is None or int(char_id) in allowed:
                pairs[i] = (
                    self.model.charset[int(char_id)],
                    to_confidence(float(score), "cnn"),
                )
            else:
                remask.append(i)
        if remask:
            idx = np.asarray(remask, dtype=np.int64)
            x = glyphs[idx].astype(np.float32)[:, None, :, :] * (1.0 / 255.0)
            logits = forward(x, self.model.weights)
            for k, i in enumerate(remask):
                char, conf = pick(logits[k], self.model.charset, allowed)
                pairs[i] = (char, to_confidence(conf, "cnn"))
        return [p for p in pairs if p is not None]

    def _classify_hybrid(
        self,
        candidates: list[VisualCandidate],
        glyphs: NDArray[np.uint8],
        allowed: set[int] | None,
        soft: NDArray[np.uint8] | None = None,
        geometries: list[tuple[float, float] | None] | None = None,
    ) -> list[tuple[str, float]]:
        """Three-level strategy: template (margin-gated) -> CNN -> unknown."""
        if not candidates:
            return []
        scores = self._scorer.score(
            [c.segment for c in candidates],
            allowed,
            soft=soft,
            geometries=geometries,
        )
        pairs: list[tuple[str, float]] = []
        for score in scores:
            if score.char_id < 0:
                char = UNKNOWN_CHAR
                conf = 0.0
            elif score.score_type == "cnn" and score.raw_score < self._cnn_threshold:
                char = UNKNOWN_CHAR  # Level 3: unknown
                conf = score.visual_score
            else:
                char = self.model.charset[int(score.char_id)]
                conf = score.visual_score
            pairs.append((char, conf))
        return pairs

    def _candidate_char(self, candidate: VisualCandidate) -> str:
        """Visible character for one chosen lattice candidate."""
        score = candidate.score
        if score is None or score.char_id < 0:
            return UNKNOWN_CHAR
        if (
            score.score_type == "cnn"
            and score.raw_score < getattr(self, "_cnn_threshold", 0.0)
        ):
            return UNKNOWN_CHAR
        return self.model.charset[int(score.char_id)]

    def _alternatives(self, paths: list[DecodePath]) -> tuple[str, ...]:
        """Single-substitution alternatives from each candidate's Top-K."""
        out: list[str] = []
        for path in paths:
            chars = [self._candidate_char(c) for c in path.candidates]
            base = "".join(chars)
            for i, cand in enumerate(path.candidates):
                scores = cand.scores
                if scores is None or len(scores.char_ids) < 2:
                    continue
                second_id = int(scores.char_ids[1])
                if second_id < 0 or second_id >= len(self.model.charset):
                    continue
                alt = list(chars)
                alt[i] = self.model.charset[second_id]
                text = "".join(alt)
                if text != base and text not in out:
                    out.append(text)
        return tuple(out[:8])
