"""Public FixedFontOCR API."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import numpy as np
from numpy.typing import NDArray

from .classifier import Classifier, TemplateClassifier
from .cnn import TinyCNNClassifier
from .model import load_model
from .preprocess import preprocess
from .types import OCRResult, Profile, default_profile


@dataclass
class FixedFontOCR:
    """Fixed-font OCR engine.

    Parameters
    ----------
    model_path:
        Directory containing ``config.json``, ``charset.txt`` and
        ``weights.bin`` (generated by ``fixedfontocr-generate``).
    backend:
        ``"auto"`` selects the CPU implementation for now; ``"cpu"`` forces it.
        ``"wgpu"`` is reserved for the future WGPU backend.
    profile:
        Segmentation profile. When ``None``, a default profile is used.
    """

    model_path: str | Path
    backend: str = "auto"
    profile: Profile | None = None

    def __post_init__(self) -> None:
        if self.backend not in ("auto", "cpu"):
            raise ValueError(
                f"backend {self.backend!r} is not implemented yet; use 'cpu' or 'auto'"
            )
        self.model = load_model(Path(self.model_path))
        self.profile = self.profile or default_profile()
        if self.model.classifier == "tinycnn":
            self._classifier: Classifier = TinyCNNClassifier(
                weights=self.model.weights,
                charset=self.model.charset,
                input_size=self.model.input_size,
            )
        else:
            self._classifier = TemplateClassifier(
                templates=self.model.templates,
                charset=self.model.charset,
                input_size=self.model.input_size,
            )

    def recognize(self, image: NDArray[np.uint8]) -> OCRResult:
        """Recognize horizontal, single-line text in ``image``.

        ``image`` must have shape ``(H, W, 3)`` and dtype ``uint8``.
        """
        image = np.asarray(image)
        if image.ndim != 3 or image.shape[2] != 3:
            raise ValueError(f"expected RGB image with shape (H, W, 3), got {image.shape}")
        if image.dtype != np.uint8:
            raise ValueError(f"expected uint8 image, got {image.dtype}")

        chars, text = preprocess(
            image,
            profile=self.profile,
            classify=self._classifier,
        )
        if not text:
            return OCRResult(text="", confidence=0.0, chars=())
        confidence = float(np.mean([c.confidence for c in chars]))
        return OCRResult(text=text, confidence=confidence, chars=tuple(chars))
